# Generated by Django 5.1.4 on 2025-01-10 03:41

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_olimpiada'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oquv_binolari', models.IntegerField()),
                ('Pedagog_xodimlar', models.IntegerField()),
                ('Oliy_va_birinchi_toifali_pedagoglar', models.IntegerField()),
                ('Kompyuter_xonalari', models.IntegerField()),
                ('Laboratoriya', models.IntegerField()),
                ('Oquvchilar', models.IntegerField()),
            ],
            options={
                'verbose_name': "Maktab ma'lumotlari",
                'verbose_name_plural': "Maktab ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maktab_direktori', models.CharField(max_length=300)),
                ('Oquv_tarbiya_Ishlari_boyicha_Direktor_Orinbosari', models.CharField(max_length=300)),
                ('Manaviy_marifiy_Ishlar_boyicha_Direktor_Orinbosari', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Raxbariyat',
                'verbose_name_plural': 'Raxbariyat',
            },
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Asosiy rasm')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalish",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='YonalishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name="Qo'shimcha rasm")),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.yonalish', verbose_name='Yonalish')),
            ],
            options={
                'verbose_name': 'Rasmlar',
                'verbose_name_plural': 'Rasmlar',
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.category')),
            ],
            options={
                'verbose_name': 'Category Translation',
                'db_table': 'app_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='YonalishTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('sarlavha', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('matn', models.TextField(verbose_name='Matn')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.yonalish')),
            ],
            options={
                'verbose_name': "Yo'nalish Translation",
                'db_table': 'app_yonalish_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
