# Generated by Django 5.2.8 on 2026-02-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_aboutschool_category_leadership_yonalish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yonalish',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video fayl'),
        ),
    ]
